#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2011 Loic Jaquemet loic.jaquemet+python@gmail.com
#

__author__ = "Loic Jaquemet loic.jaquemet+python@gmail.com"

__doc__ = '''
  Reverse heap analysis.
'''

import os, sys

if __name__ == "__main__":
  sys.path.append(os.getcwd())
  from haystack.reverse import reversers 
  reversers.main(sys.argv[1:])


